kafka_store:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'workspace') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'kafka_store_v5_dbt') }}"
      host: "{{ env_var('DATABRICKS_HOST') | replace('https://', '') | replace('/', '') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4